/*
 * This source file was generated by the Gradle 'init' task
 */
package cities;

import javax.swing.SwingUtilities;
import cities.controller.AppController;

public class App {

    public static void main(String[] args) {
        SwingUtilities.invokeLater(() -> {
            
            AppController app = new AppController();
            app.start();
        });
    }
}
